agregator/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^video/', include('videos.urls')),
    url(r'^accounts/', include('registration.backends.default.urls')),
]

videos/urls.py
# coding=utf-8
from __future__ import unicode_literals
from django.conf.urls import url

from .views import ShowUrlVideosView, ShowVideosView, AddUserTaskView

urlpatterns = [
    url(r'^add_task/', AddUserTaskView.as_view(), name='add_user_task'),
    url(r'^show_task/', ShowUrlVideosView.as_view(), name='show_user_task'),
    url(r'^show_result', ShowVideosView.as_view(), name='show_result'),
]

videos/models.py
# coding=utf-8
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models


class UserTask(models.Model):
    owner = models.ForeignKey(User)
    site_url = models.URLField(max_length=300)
    site_tags = models.CharField(max_length=100)

    def __unicode__(self):
        return self.site_url


class ParsedUrl(models.Model):
    url = models.ForeignKey(UserTask)
    urls = models.CharField(max_length=400)
    is_created_video = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.urls


class Videos(models.Model):
    owner = models.ForeignKey(User)
    video = models.FileField(upload_to='upload/video/%Y_%m_%d/')

    def __unicode__(self):
        return str(self.owner)

videos/forms.py
# coding=utf-8
from __future__ import unicode_literals
from django import forms

from videos.models import UserTask


class UserTaskForm(forms.ModelForm):
    class Meta:
        model = UserTask
        fields = ('site_url', 'site_tags', )
        widgets = {
            'site_url': forms.TextInput(attrs={'class': 'form-control'}),
            'site_tags': forms.TextInput(attrs={'class': 'form-control'})
        }

videos/views.py
# coding=utf-8
from __future__ import unicode_literals
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.utils.decorators import method_decorator
from django.views.generic import ListView, FormView

from videos.forms import UserTaskForm
from videos.models import UserTask, Videos, ParsedUrl
from videos.tasks import make_content


class BaseMixin(object):
    js = []
    css = []
    title = ''

    def get_context_data(self, **kwargs):
        context = super(BaseMixin, self).get_context_data(**kwargs)
        context['additional_scripts'] = self.js
        context['additional_css'] = self.css
        context['title'] = self.title

        return context

class AddUserTaskView(BaseMixin, FormView):
    model = UserTask
    template_name = 'add_video.html'
    form_class = UserTaskForm
    title = 'Добавьте ссылку для видео'

    def form_valid(self, form):
        tasks = [task.site_url for task in UserTask.objects.filter(owner=self.request.user)]
        if form.cleaned_data['site_url'] not in tasks:
            form.instance.owner = self.request.user
            form.save()
            make_content.delay(form.cleaned_data['site_url'],
                               form.cleaned_data['site_tags'])
            return JsonResponse({'status': 'ok', })

        return JsonResponse({'status': 'already_exist', })

    def form_invalid(self, form):
        return JsonResponse({'status': 'error', 'errors': form.errors})

class ShowUrlVideosView(BaseMixin, ListView):
    model = ParsedUrl
    template_name = 'detail.html'
    title = 'Список ваших УРЛов'

    def get_context_data(self, **kwargs):
        context = super(ShowUrlVideosView, self).get_context_data(**kwargs)
        context['user_urls'] = UserTask.objects.filter(owner=self.request.user)
        return context

class ShowVideosView(BaseMixin, ListView):
    model = Videos
    template_name = 'detail_videos.html'
    title = 'Список ваших Видео'

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
    <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="keywords" content="Agregator">
    <title>
        {{ title }}
    </title>
    {% if additional_css %}
        {% for css in additional_css %}
          <link rel="stylesheet" type="text/css" href="{{ css }}">
        {% endfor %}
    {% endif %}

    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/css.css' %}" />
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    </head>
<body>

    {% include 'template_scripts.html' %}
    {% if additional_scripts %}
        {% for script_name in additional_scripts %}
          <script src="{{ script_name }}"></script>
        {% endfor %}
    {% endif %}

    {% include 'header.html' %}
    <div class="container">
    {% block content %}{% endblock %}
    </div>
  </body>
</html>

templates/header.html
{% load staticfiles %}
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'add_user_task' %}"> Tasks Parser </a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
    {% if request.user.is_authenticated %}
      <ul class="nav navbar-nav">
        <li><a href="{% url 'add_user_task' %}">Add task</a></li>
        <li><a href="{% url 'show_user_task' %}">View tasks</a></li>
        <li><a href="{% url 'show_result' %}">View videos</a></li>
      </ul>
    {% endif %}

      <ul class="nav navbar-nav navbar-right">
          {% if request.user.is_authenticated %}
            <li><a href="#">{{ request.user }}</a></li>
            <li><a href="{% url 'auth_logout' %}">Logout</a></li>
          {% else %}
            <li><a href="{% url 'registration_register' %}">Register</a></li>
          {% endif %}
      </ul>

        {% if not request.user.is_authenticated and not '/accounts/login' in request.get_full_path %}
        <form class="navbar-form navbar-right" method="post" action="{% url 'auth_login' %}">{% csrf_token %}
            <div class="form-group">
                <input type="text" class="form-control" name="username" placeholder="Username" />
            </div>
            <div class="form-group">
                <input type="password" class="form-control" name="password" placeholder="Password" />
            </div>
            <button type="submit" class="btn btn-default">Login</button>
        </form>
        {% endif %}
    </div>
  </div>
</nav>

templates/left_sidebar.html
{% url 'add_url_video'  as add_url_video %}
{% url 'show_url_video' as show_url_video %}
{% url 'show_video' as show_video %}


<nav class="navmenu navmenu-default" role="navigation">
    <h4>
        <ul class="nav navmenu-nav">
            <li class="{% if request.get_full_path == add_url_video %}active{% endif %}"><a href="{{ add_url_video }}">ADD URL</a></li>
        </ul>
        <ul class="nav navmenu-nav">
            <li class="{% if request.get_full_path == show_url_video %}active{% endif %}"><a href="{{ show_url_video }}">SHOW URL</a></li>
        </ul>
        <ul class="nav navmenu-nav">
            <li class="{% if request.get_full_path == show_video %}active{% endif %}"><a href="{{ show_video }}">ADD URL</a></li>
        </ul>
    </h4>
</nav>

templates/template_scripts.html
{% load staticfiles %}
    <script src="{% static 'js/jquery-1.11.3.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/js.js' %}"></script>

videos/templates/add_video.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% load staticfiles %}


    {% block content %}

    {% if request.user.is_authenticated %}

        <div class="row">
            <div class="col-sm-12">
                <form class='add-url-form' id='add-url-form'  method='POST' action='{% url 'add_user_task' %}'>
                    {% csrf_token %}
                    {{ form|crispy }}
                    <input class="btn btn-default" type="submit" value="Submit">
                    <div>
                        <h3><span id="success_text" class="text-success">New URL was successfully added</span></h3>
                    </div><div>
                        <h3><span id="already_exists_text" class="text-danger">This URL is already in your tasks!</span></h3>
                    </div>

                </form>
            </div>
        </div>

{#        <form class='add-url-form' id='add-url-form' action="{% url 'add_user_task' %}" method="post">#}
{##}
{#            <div class="message"></div>#}
{#            {% csrf_token %}#}
{##}
{#            <div class="fieldWrapper row sky-space-20">#}
{#                <div class="col-md-12 col-md-offset-0">#}
{#                  <label class="text-success" for="id_site_url">Введите url:</label>#}
{##}
{#                    <div id="site_url_text" class="has-success form-group">#}
{#                      {{ form.site_url }}#}
{#                      <span id="site_url_error_text" class="help-inline">{{ form.site_url.errors }}</span>#}
{#                    </div>#}
{##}
{#                </div>#}
{#            </div>#}
{##}
{#            <div class="fieldWrapper row sky-space-20">#}
{#                <div class="col-md-2 col-md-offset-0">#}
{#                  <label class="text-success" for="id_site_tags">Введите тег:</label>#}
{#                    <div id="site_tags_text" class="has-success form-group">#}
{#                      {{ form.site_tags }}#}
{#                      <span id='site_tags_error_text' class="help-inline">{{ form.site_tags.errors }}</span>#}
{#                    </div>#}
{#                </div>#}
{#            </div>#}
{##}
{##}
{#            <input class="btn btn-success" id='submit-button' type="submit" value="Submit">#}
{#            <div>#}
{#                <h3><span id="success_text" class="text-success">New URL was successfully added</span></h3>#}
{#            </div><div>#}
{#                <h3><span id="already_exists_text" class="text-danger">This URL is already in your tasks!</span></h3>#}
{#            </div>#}
{#        </form>#}

    {% else %}
        <h1> You need to register to do something</h1>
    {% endif %}

    {% endblock %}

videos/templates/detail.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block content %}

    {% if user_urls %}

        <ol>
            {% for url in user_urls %}
                <li>
                    <p>
                        {{ url }}
                        {% for item in parsedurl_list %}
                        {% endfor %}
                    </p>
                </li>
            {% endfor %}
        </ol>

    {% else %}

        <h3>
            Please add some <a href="{% url 'add_user_task' %}">url</a>
        </h3>

    {% endif %}
{% endblock %}

videos/templates/detail_videos.html
{% extends 'base.html' %}

{% block content %}

    <h1>
        Здесь будут отображаться результаты обработки видео
    </h1>

{% endblock %}